"use strict";
// import { oil , add, obj as myObj , newArray} from "./app";
Object.defineProperty(exports, "__esModule", { value: true });
var practice = require("./app");
console.log(practice.oil);
// import { add } from "./app";
var res = practice.add(2, 3);
console.log(res);
// import { obj as myObj } from "./app";
// console.log(myObj);
console.log(practice.obj);
// import { newArray } from "./app";
console.log(practice.newArray);
